# This is a basic workflow to deploy your Terraform configuration, after it has been validated

name: deploy

# Controls when the workflow will run
on:
  # Triggers the workflow on push request events
  push:
    branches:
      - 'main'
    paths:
      - 'oving9/infra/**'  #path in gitrepo



# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "deploy"
  terraform:
    runs-on: ubuntu-22.04
    #name: 'deploy infrastructure'
    # The type of runner that the job will run on
    env:
      ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
      SSH_PUBLIC_KEY: ${{ secrets.SSH_PUBLIC_KEY }}
      WORKING_DIR: ./oving9/infra  #legg til sti

      #steps/secquence of tasks for the job
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1
        
      #initialize Terraform
      - name: Terraform init
        id: init
        run: terraform init
        working-directory: ${{ env.WORKING_DIR }}
     
      #Terraform plan
      - name: Terrform plan
        id: plan 
        run: terraform plan -var="ssh_public_key=${SSH_PUBLIC_KEY}"
        working-directory: ${{ env.WORKING_DIR }}

      #Terraform apply
      - name: Terraform Apply
        id: apply
        run: terraform apply -var="ssh_public_key=${SSH_PUBLIC_KEY}" -auto-approve
        working-directory: ${{ env.WORKING_DIR }}

